config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  root to: 'vaccinations#index'
  resource :vaccinations, only: %i[new create destroy]
  post 'search_record', to: 'vaccinations#search'
  get 'search_record', to: 'vaccinations#index'

  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
# frozen_string_literal: true

class Country < ApplicationRecord
  has_many :users, dependent: :destroy
  has_many :vaccinations, dependent: :destroy
end

app/models/csv_upload.rb
# frozen_string_literal: true

class CsvUpload < ApplicationRecord
  belongs_to :user
  has_one_attached :csv
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :country
  has_many :csv_uploads, dependent: :destroy
end

app/models/vaccination.rb
# frozen_string_literal: true

class Vaccination < ApplicationRecord
  belongs_to :country
  has_many :vaccination_vaccines, dependent: :destroy

  enum data_source: { REPORTING: 0, OWID: 1 }

  validates_associated :country, :vaccination_vaccines
end

app/models/vaccination_vaccine.rb
# frozen_string_literal: true

class VaccinationVaccine < ApplicationRecord
  belongs_to :vaccination
  belongs_to :vaccine
end

app/models/vaccine.rb
# frozen_string_literal: true

class Vaccine < ApplicationRecord
  has_many :vaccinations_vaccine, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

module Users
  class RegistrationsController < Devise::RegistrationsController
    before_action :configure_sign_up_params, only: [:create]
    # before_action :configure_account_update_params, only: [:update]
    before_action :set_countries, only: %i[new create]

    # GET /resource/sign_up
    def new
      super
    end

    # POST /resource
    def create
      super
    end

    # GET /resource/edit
    # def edit
    #   super
    # end

    # PUT /resource
    # def update
    #   super
    # end

    # DELETE /resource
    # def destroy
    #   super
    # end

    # GET /resource/cancel
    # Forces the session data which is usually expired after sign
    # in to be expired now. This is useful if the user wants to
    # cancel oauth signing in/up in the middle of the process,
    # removing all OAuth session data.
    # def cancel
    #   super
    # end

    protected

    # If you have extra params to permit, append them to the sanitizer.
    def configure_sign_up_params
      devise_parameter_sanitizer.permit(:sign_up, keys: [:country_id])
    end

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_account_update_params
    #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
    # end

    # The path used after sign up.
    # def after_sign_up_path_for(resource)
    #   super(resource)
    # end

    # The path used after sign up for inactive accounts.
    # def after_inactive_sign_up_path_for(resource)
    #   super(resource)
    # end

    def set_countries
      @countries = Country.order(:name).all
    end
  end
end

app/controllers/vaccinations_controller.rb
# frozen_string_literal: true

class VaccinationsController < ApplicationController
  rescue_from ActionController::ParameterMissing, with: :require_params
  before_action :authenticate_user!, except: %i[index search]
  before_action :set_vaccination, only: %i[index new create search]
  before_action :vaccination_params, only: %i[create]
  before_action :search_params, only: %i[search]
  before_action :set_data, only: %i[index search]

  def index; end

  def new; end

  def create
    if upload_csv_to_local
      AddVaccination.perform_async(@csv_path)
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    # delete all uploaded csv files
    CsvUpload.delete_all
    ActiveStorage::Attachment.all.each(&:purge)

    RemoveVaccination.perform_async
  end

  def search
    @search_vaccination = SearchVaccination.new(params[:vaccination])
    @vaccinations = @search_vaccination.call
    # set_search_params
    render :index
  end

  private

  def set_vaccination
    @vaccination = Vaccination.new
    @vaccination_vaccine = @vaccination.vaccination_vaccines.build
  end

  def vaccination_params
    params.require(:vaccination).permit(:file)
  end

  def search_params
    params.require(:vaccination).permit(:country, :data_source, :date_updated, :vaccines,
                                        :first_vaccine_date, vaccination_vaccine: [:vaccine])
  end

  def require_params
    flash[:alert] = "The file field is required."
    redirect_to new_vaccinations_path
  end

  def upload_csv_to_local
    file = params[:vaccination][:file]

    return false unless csv?(file)

    vac = CsvUpload.create!(user_id: current_user.id)
    vac.csv.attach(file)
    @csv_path = vac.csv.url
  rescue URI::InvalidURIError
    # do nothing
  end

  def csv?(file)
    if File.extname(file) == ".csv"
      true
    else
      flash[:alert] = "Please upload a valid CSV file"
      false
    end
  end

  def set_data
    @vaccinations = Vaccination.all
    @countries = Country.order(:name).all
    @data_sources = Vaccination.data_sources
    @vaccines = Vaccine.order(:name).all
    @search_vaccination = SearchVaccination.new(nil)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/_alerts.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show container mt-3 fixed-alert" id="success-alert" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>

<% elsif alert %>
  <div class="alert alert-danger alert-dismissible fade show container mt-3 fixed-alert" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>

<% elsif flash[:errors] %>
  <% flash[:errors].each do |message| %>
    <div class="alert alert-danger alert-dismissible fade show container mt-3 fixed-alert" role="alert">
      <%= message %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
<% end %>

<div class="alert alert-success alert-dismissible fade show container mt-3 fixed-alert" id="success-alert" role="alert" style="display:none">
  <span id="success-alert-msg">Alert message goes here...</span> <%= link_to "Click to reload data.", root_path %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      Covid Data App
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to destroy_user_session_path, method: :delete, class: "nav-link" do %>
              Logout
            <% end %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to new_user_registration_path, class: "nav-link" do %>
              Register
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_user_session_path, class: "nav-link" do %>
              Login
            <% end %>
          </li>
        <% end %>
      </ul>
      <span class="navbar-text">
        <% if user_signed_in? %>
          <%= current_user.email %> | <%= current_user.country.name %>
        <% end %>
      </span>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <title>Covid Data App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "/layouts/navbar" %>
    <%= render "/layouts/alerts" %>

    <div class="container-fluid">
      <%= yield %>
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/vaccinations/_search.html.erb
<%= simple_form_for :vaccination, url: search_record_path, method: :post do |f| %>
  <div class="row pt-2 pb-3 mb-4 p-5 bg-secondary text-white">
    <div class="col">
      <label class="form-label">Country:</label>
      <%= f.input :country, collection: locals[:countries], :selected => locals[:country], :include_blank => "-Select Country-", input_html: { class: "form-control" }, label: false %>
    </div>

    <div class="col">
      <label class="form-label">Data Source:</label>
      <%= f.input :data_source, collection: locals[:data_sources], :selected => locals[:data_source], :include_blank => "-Select Data Source-", input_html: { class: "form-control" }, label: false %>
    </div>

    <div class="col">
      <label class="form-label">Date Updated:</label>
      <%= f.text_field :date_updated, value: locals[:date_updated], class: "form-control",
        data: {
          mode: "range",
          controller: "flatpickr",
          flatpickr_date_format: "Y-m-d"
        }
      %>
    </div>

    <div class="col">
      <%= f.fields_for :vaccination_vaccine do |vvf| %>
        <label class="form-label">Vaccines Used:</label>
        <%= vvf.input :vaccine, collection: locals[:vaccines], :selected => locals[:vaccine], :include_blank => "-Select Vaccine-", input_html: { class: "form-control" }, label: false %>
      <% end %>
    </div>

    <div class="col">
      <label class="form-label">Date First Vaccinated:</label>
      <%= f.text_field :first_vaccine_date, value: locals[:first_vaccine_date], class: "form-control",
        data: {
          mode: "range",
          controller: "flatpickr",
          flatpickr_date_format: "Y-m-d"
        }
      %>
    </div>

    <div class="col">
      <label class="form-label">&nbsp;</label>
      <div class="row">
        <%= f.button :submit, "SEARCH", class: "btn btn-dark btn-block" %>
      </div>
    </div>
  </div>
<% end %>

app/views/vaccinations/index.html.erb
<div class="row pt-4 pb-4 bg-image">
  <div class="col-md-12">
    <h3 class="text-white">Vaccinations Record</h3>
    <% if user_signed_in? %>
      <div class="btn-group float-end">
        <%= link_to "Upload Record", new_vaccinations_path, class: "btn btn-dark" %>
        <%= link_to 'Delete All Records', vaccinations_path, class: "btn btn-danger", method: :delete, data: {confirm: "Are you sure?"} %>
      </div>
    <% end %>
  </div>
</div>

<%= render "vaccinations/search",
  locals: {
    countries: @countries, data_sources: @data_sources, vaccines: @vaccines,
    country: @search_vaccination.country, data_source: @search_vaccination.data_source,
    date_updated: @search_vaccination.date_updated, vaccine: @search_vaccination.vaccine,
    first_vaccine_date: @search_vaccination.first_vaccine_date
  }
%>

<table class="table table-hover">
  <thead>
    <tr>
      <th>#</th>
      <th>Country</th>
      <th>ISO3</th>
      <th>Data Source</th>
      <th>Date Updated</th>
      <th>Total Vaccinations</th>
      <th>Persons Vaccinated 1 Plus Dose</th>
      <th>Total Vaccinations per 100</th>
      <th>Vaccines Used</th>
      <th>First Vaccine Date</th>
      <th>Number of Vaccine Type Used</th>
    </tr>
  </thead>
  <tbody>
    <% counter = 0  %>
    <% @vaccinations.each do |v| %>
      <tr>
        <td><%= counter = counter.to_i + 1 %></td>
        <td><%= v.country.name %></td>
        <td><%= v.country.iso3 %></td>
        <td><%= v.data_source %></td>
        <td><%= v.date_updated %></td>
        <td><%= v.total_vaccinations %></td>
        <td><%= v.persons_vaccinated_1plus_dose %></td>
        <td><%= v.total_vaccinations_per100 %></td>
        <td>
          <% v.vaccination_vaccines.each do |vv| %>
            <span class="row"><%= vv.vaccine.name %>,</span>
          <% end %>
        </td>
        <td><%= v.first_vaccine_date %></td>
        <td><%= v.number_vaccines_types_used %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/vaccinations/new.html.erb
<div class="row">
  <div class="col-sm-4"></div>
  <div class="col-sm-4">
    <div class="card mt-5">
      <h3 class="card-header text-center">Import CSV</h3>
      <div class="card-body">
        <%= simple_form_for @vaccination do |f| %>
          <div class="form-group mb-3">
            <%= f.input :file, as: :file, input_html: { class: 'form-control', accept: "text/csv" }, label: false %>
          </div>

          <div class="row p-3">
            <%= f.button :submit, "Upload CSV File", class: "btn btn-dark btn-block" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>